version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/Java-API

    steps:
      - checkout

      - run:
          name: go to
          command: |
            echo "Current directory: $PWD"
      - run:
          name: Install ddd
          command: cd Java-API
      - run:
          name: Install Dependencies
          command: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - run:
          name: Run Integration Tests
          command: mvn failsafe:integration-test

      - run:
          name: Generate Reports
          command: mvn serenity:aggregate

workflows:
  version: 2
  build:
    jobs:
      - build