version: 2.1

jobs:
  java-job:
    docker:
      - image: circleci/openjdk:17.0.1-buster
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd Java-API && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Run Tests
          command: cd Java-API && mvn failsafe:integration-test
      - run:
          name: GENERATE REPORT
          command: cd Java-API && mvn serenity:aggregate
      - store_artifacts:
          path: Java-API/target/site
          destination: java-artifacts

  node-js-job:
    docker:
      - image: timbru31/java-node:latest
    steps:
      - checkout
      - run:
          name: Get access
          command: cd CypressApi && chmod 777  /root
      - run:
          name: Update dependencies
          command: cd CypressApi && apt update && apt upgrade -y
      - run:
          name: Install libs
          command: cd CypressApi && apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
      - run:
          name: Update cypress
          command: cd CypressApi && npm install cypress --save-dev
      - run:
          name: install all
          command: cd CypressApi && npm i
      - run:
          name: run tests
          command: cd CypressApi && npm run cy:run || true
      - run:
          name: generate report
          command: cd CypressApi && npm run allure:report
      - store_artifacts:
          path: CypressApi/allure-report
          destination: CypressReport

  python-job:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: generate report
          command: cd API-Testing-Pytest-main && pip install -r requirements.txt
      - run:
          name: run tests
          command: cd API-Testing-Pytest-main && pytest Tests --html=report.html --self-contained-html
      - store_artifacts:
          path: API-Testing-Pytest-main/report.html
          destination: python-report

workflows:
  build-and-test:
    jobs:
      - java-job
      - node-js-job
      - python-job