version: 2.1

jobs:
  java-job:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd Java-API && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Run Tests
          command: cd Java-API && mvn failsafe:integration-test
      - run:
          name: GENERATE REPORT
          command: cd Java-API && mvn serenity:aggregate


  node-js-job:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd cypressApi && npm install && npm run build

  python-job:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: cd Python-project && pip install -r requirements.txt && python tests.py

workflows:
  build-and-test:
    jobs:
      - java-job
      - node-js-job
      - python-job